const fs = require('fs');
const path = require('path');
const dir = __dirname;
const files = fs.readdirSync(dir).filter(f => f.endsWith('.html'));
files.forEach(f => {
    let content = fs.readFileSync(path.join(dir, f), 'utf-8');
    content = content.replaceAll('œ¦', '');
    content = content.replaceAll('Â·', '-');
    content = content.replaceAll('â—ˆ', '*');
    content = content.replaceAll('â—‰', '*');
    content = content.replaceAll('â†’', '>');
    content = content.replaceAll('â†', '<');
    content = content.replaceAll('â€œ', '"');
    content = content.replaceAll('â€', '"');
    content = content.replaceAll('â€™', "'");
    content = content.replaceAll('Â', '');
    content = content.replaceAll('â', '');
    content = content.replaceAll('œ', '');
    content = content.replaceAll('¦', '');
    content = content.replaceAll('€', '');
    content = content.replaceAll('“', '"');
    content = content.replaceAll('”', '"');
    content = content.replaceAll('‘', "'");
    content = content.replaceAll('’', "'");
    content = content.replaceAll('·', '-');
    content = content.replaceAll('—', '-');
    content = content.replaceAll('–', '-');
    content = content.replaceAll('…', '...');
    content = content.replaceAll('15 February - 30 April 2026', '15 February - 30 April 2026');
    content = content.replaceAll('09:00"18:00', '09:00 - 18:00');
    content = content.replaceAll('<span class="ticker-sep"></span>', '<span class="ticker-sep">***</span>');
    fs.writeFileSync(path.join(dir, f), content, 'utf-8');
});
console.log('Clean completed');
